// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: scheduler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskKind int32

const (
	TaskKind_TASK_NONE     TaskKind = 0 // 无任务，按 message 退避轮询
	TaskKind_TASK_SELFPLAY TaskKind = 1
	TaskKind_TASK_RATING   TaskKind = 2 // gatekeeper / rating 对打
)

// Enum value maps for TaskKind.
var (
	TaskKind_name = map[int32]string{
		0: "TASK_NONE",
		1: "TASK_SELFPLAY",
		2: "TASK_RATING",
	}
	TaskKind_value = map[string]int32{
		"TASK_NONE":     0,
		"TASK_SELFPLAY": 1,
		"TASK_RATING":   2,
	}
)

func (x TaskKind) Enum() *TaskKind {
	p := new(TaskKind)
	*p = x
	return p
}

func (x TaskKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskKind) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_proto_enumTypes[0].Descriptor()
}

func (TaskKind) Type() protoreflect.EnumType {
	return &file_scheduler_proto_enumTypes[0]
}

func (x TaskKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskKind.Descriptor instead.
func (TaskKind) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

// worker 拉取任务请求（含机器规格，服务端按规格匹配任务量）
type TaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ClientVersion  string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Threads        int32                  `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`                                    // 可用线程数
	MemoryMb       int64                  `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`                  // 可用内存
	CurrentNetwork string                 `protobuf:"bytes,5,opt,name=current_network,json=currentNetwork,proto3" json:"current_network,omitempty"` // 本地已有网络 sha（空表示需要下载）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *TaskRequest) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *TaskRequest) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *TaskRequest) GetCurrentNetwork() string {
	if x != nil {
		return x.CurrentNetwork
	}
	return ""
}

// 任务响应
type TaskResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Kind             TaskKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=scheduler.TaskKind" json:"kind,omitempty"`
	NetworkSha       string                 `protobuf:"bytes,3,opt,name=network_sha,json=networkSha,proto3" json:"network_sha,omitempty"`                     // 主网络（训练网络）
	OpponentSha      string                 `protobuf:"bytes,4,opt,name=opponent_sha,json=opponentSha,proto3" json:"opponent_sha,omitempty"`                  // rating 对打时的对手网络；selfplay 为空
	NetworkUrl       string                 `protobuf:"bytes,5,opt,name=network_url,json=networkUrl,proto3" json:"network_url,omitempty"`                     // R2 预签名下载 URL（主网络）
	OpponentUrl      string                 `protobuf:"bytes,6,opt,name=opponent_url,json=opponentUrl,proto3" json:"opponent_url,omitempty"`                  // 对手网络下载 URL
	NetworkShaRemote string                 `protobuf:"bytes,7,opt,name=network_sha_remote,json=networkShaRemote,proto3" json:"network_sha_remote,omitempty"` // 服务端当前 best sha（用于本地缓存比对）
	Games            int32                  `protobuf:"varint,8,opt,name=games,proto3" json:"games,omitempty"`                                                // 本批对局数
	Params           *SelfPlayParams        `protobuf:"bytes,9,opt,name=params,proto3" json:"params,omitempty"`
	Message          string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"` // 无任务时的说明（task_waiting 等）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetKind() TaskKind {
	if x != nil {
		return x.Kind
	}
	return TaskKind_TASK_NONE
}

func (x *TaskResponse) GetNetworkSha() string {
	if x != nil {
		return x.NetworkSha
	}
	return ""
}

func (x *TaskResponse) GetOpponentSha() string {
	if x != nil {
		return x.OpponentSha
	}
	return ""
}

func (x *TaskResponse) GetNetworkUrl() string {
	if x != nil {
		return x.NetworkUrl
	}
	return ""
}

func (x *TaskResponse) GetOpponentUrl() string {
	if x != nil {
		return x.OpponentUrl
	}
	return ""
}

func (x *TaskResponse) GetNetworkShaRemote() string {
	if x != nil {
		return x.NetworkShaRemote
	}
	return ""
}

func (x *TaskResponse) GetGames() int32 {
	if x != nil {
		return x.Games
	}
	return 0
}

func (x *TaskResponse) GetParams() *SelfPlayParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *TaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SelfPlayParams struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MctsSims         int32                  `protobuf:"varint,1,opt,name=mcts_sims,json=mctsSims,proto3" json:"mcts_sims,omitempty"`
	Temperature      float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	PlayoutCapRandom bool                   `protobuf:"varint,3,opt,name=playout_cap_random,json=playoutCapRandom,proto3" json:"playout_cap_random,omitempty"`
	Variant          string                 `protobuf:"bytes,4,opt,name=variant,proto3" json:"variant,omitempty"`                            // 4x8 / 4x4 / 4x2
	ExtraConfig      string                 `protobuf:"bytes,5,opt,name=extra_config,json=extraConfig,proto3" json:"extra_config,omitempty"` // JSON 透传
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SelfPlayParams) Reset() {
	*x = SelfPlayParams{}
	mi := &file_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfPlayParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfPlayParams) ProtoMessage() {}

func (x *SelfPlayParams) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfPlayParams.ProtoReflect.Descriptor instead.
func (*SelfPlayParams) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *SelfPlayParams) GetMctsSims() int32 {
	if x != nil {
		return x.MctsSims
	}
	return 0
}

func (x *SelfPlayParams) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SelfPlayParams) GetPlayoutCapRandom() bool {
	if x != nil {
		return x.PlayoutCapRandom
	}
	return false
}

func (x *SelfPlayParams) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *SelfPlayParams) GetExtraConfig() string {
	if x != nil {
		return x.ExtraConfig
	}
	return ""
}

// episode 元数据上报：服务端只收元数据 + 签发 R2 预签名 PUT，数据直传 R2
type EpisodeMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	GameCount     int32                  `protobuf:"varint,3,opt,name=game_count,json=gameCount,proto3" json:"game_count,omitempty"`
	TotalSteps    int32                  `protobuf:"varint,4,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	Winner        int32                  `protobuf:"varint,5,opt,name=winner,proto3" json:"winner,omitempty"` // 1 红 / -1 黑 / 0 平；rating 任务另有字段
	NetworkSha    string                 `protobuf:"bytes,6,opt,name=network_sha,json=networkSha,proto3" json:"network_sha,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ContentLength int64                  `protobuf:"varint,8,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"` // 待上传对象大小
	ContentSha256 string                 `protobuf:"bytes,9,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`  // 对象 sha256（R2 强校验）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeMeta) Reset() {
	*x = EpisodeMeta{}
	mi := &file_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeMeta) ProtoMessage() {}

func (x *EpisodeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeMeta.ProtoReflect.Descriptor instead.
func (*EpisodeMeta) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *EpisodeMeta) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *EpisodeMeta) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *EpisodeMeta) GetGameCount() int32 {
	if x != nil {
		return x.GameCount
	}
	return 0
}

func (x *EpisodeMeta) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *EpisodeMeta) GetWinner() int32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *EpisodeMeta) GetNetworkSha() string {
	if x != nil {
		return x.NetworkSha
	}
	return ""
}

func (x *EpisodeMeta) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EpisodeMeta) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *EpisodeMeta) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

type EpisodeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,3,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // 预签名 PUT URL；accepted=false 时为空
	ObjectKey     string                 `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"` // R2 对象键 episodes/<sha>/<uuid>.jsonl.gz
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeAck) Reset() {
	*x = EpisodeAck{}
	mi := &file_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeAck) ProtoMessage() {}

func (x *EpisodeAck) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeAck.ProtoReflect.Descriptor instead.
func (*EpisodeAck) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *EpisodeAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EpisodeAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EpisodeAck) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *EpisodeAck) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

// 网络请求：sha 为空 = 拉取当前 best
type NetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha           string                 `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkRequest) Reset() {
	*x = NetworkRequest{}
	mi := &file_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkRequest) ProtoMessage() {}

func (x *NetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkRequest.ProtoReflect.Descriptor instead.
func (*NetworkRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkRequest) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

type NetworkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha           string                 `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // 预签名 GET URL
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsBest        bool                   `protobuf:"varint,4,opt,name=is_best,json=isBest,proto3" json:"is_best,omitempty"`
	GameData      string                 `protobuf:"bytes,5,opt,name=game_data,json=gameData,proto3" json:"game_data,omitempty"` // 训练侧附加信息（parent sha 等），JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkInfo) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *NetworkInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *NetworkInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NetworkInfo) GetIsBest() bool {
	if x != nil {
		return x.IsBest
	}
	return false
}

func (x *NetworkInfo) GetGameData() string {
	if x != nil {
		return x.GameData
	}
	return ""
}

// trainer（GPU 机）注册新网络 → 触发 gatekeeper 对打
type RegisterNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha           string                 `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	ParentSha     string                 `protobuf:"bytes,2,opt,name=parent_sha,json=parentSha,proto3" json:"parent_sha,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,3,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // trainer 已直传 R2，这里登记元数据
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNetworkRequest) Reset() {
	*x = RegisterNetworkRequest{}
	mi := &file_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNetworkRequest) ProtoMessage() {}

func (x *RegisterNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNetworkRequest.ProtoReflect.Descriptor instead.
func (*RegisterNetworkRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterNetworkRequest) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *RegisterNetworkRequest) GetParentSha() string {
	if x != nil {
		return x.ParentSha
	}
	return ""
}

func (x *RegisterNetworkRequest) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *RegisterNetworkRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type RegisterNetworkAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MatchTaskHint string                 `protobuf:"bytes,3,opt,name=match_task_hint,json=matchTaskHint,proto3" json:"match_task_hint,omitempty"` // 若已生成 gatekeeper 任务，附说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNetworkAck) Reset() {
	*x = RegisterNetworkAck{}
	mi := &file_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNetworkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNetworkAck) ProtoMessage() {}

func (x *RegisterNetworkAck) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNetworkAck.ProtoReflect.Descriptor instead.
func (*RegisterNetworkAck) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterNetworkAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterNetworkAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNetworkAck) GetMatchTaskHint() string {
	if x != nil {
		return x.MatchTaskHint
	}
	return ""
}

// 对局结果上报（selfplay 汇总 / rating 单局）
type MatchResult struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkerId    string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId      string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Kind        TaskKind               `protobuf:"varint,3,opt,name=kind,proto3,enum=scheduler.TaskKind" json:"kind,omitempty"`
	NetworkSha  string                 `protobuf:"bytes,4,opt,name=network_sha,json=networkSha,proto3" json:"network_sha,omitempty"`
	OpponentSha string                 `protobuf:"bytes,5,opt,name=opponent_sha,json=opponentSha,proto3" json:"opponent_sha,omitempty"`
	Games       int32                  `protobuf:"varint,6,opt,name=games,proto3" json:"games,omitempty"` // 本批局数
	Wins        int32                  `protobuf:"varint,7,opt,name=wins,proto3" json:"wins,omitempty"`   // 主网络视角（统计用）
	Losses      int32                  `protobuf:"varint,8,opt,name=losses,proto3" json:"losses,omitempty"`
	Draws       int32                  `protobuf:"varint,9,opt,name=draws,proto3" json:"draws,omitempty"`
	// 成对五项计数（换色配对两局一组）：rating 任务必填，selfplay 为 0
	PairLl        int32 `protobuf:"varint,10,opt,name=pair_ll,json=pairLl,proto3" json:"pair_ll,omitempty"`
	PairLd        int32 `protobuf:"varint,11,opt,name=pair_ld,json=pairLd,proto3" json:"pair_ld,omitempty"`
	PairDd        int32 `protobuf:"varint,12,opt,name=pair_dd,json=pairDd,proto3" json:"pair_dd,omitempty"`
	PairDw        int32 `protobuf:"varint,13,opt,name=pair_dw,json=pairDw,proto3" json:"pair_dw,omitempty"`
	PairWw        int32 `protobuf:"varint,14,opt,name=pair_ww,json=pairWw,proto3" json:"pair_ww,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	mi := &file_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *MatchResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *MatchResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MatchResult) GetKind() TaskKind {
	if x != nil {
		return x.Kind
	}
	return TaskKind_TASK_NONE
}

func (x *MatchResult) GetNetworkSha() string {
	if x != nil {
		return x.NetworkSha
	}
	return ""
}

func (x *MatchResult) GetOpponentSha() string {
	if x != nil {
		return x.OpponentSha
	}
	return ""
}

func (x *MatchResult) GetGames() int32 {
	if x != nil {
		return x.Games
	}
	return 0
}

func (x *MatchResult) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *MatchResult) GetLosses() int32 {
	if x != nil {
		return x.Losses
	}
	return 0
}

func (x *MatchResult) GetDraws() int32 {
	if x != nil {
		return x.Draws
	}
	return 0
}

func (x *MatchResult) GetPairLl() int32 {
	if x != nil {
		return x.PairLl
	}
	return 0
}

func (x *MatchResult) GetPairLd() int32 {
	if x != nil {
		return x.PairLd
	}
	return 0
}

func (x *MatchResult) GetPairDd() int32 {
	if x != nil {
		return x.PairDd
	}
	return 0
}

func (x *MatchResult) GetPairDw() int32 {
	if x != nil {
		return x.PairDw
	}
	return 0
}

func (x *MatchResult) GetPairWw() int32 {
	if x != nil {
		return x.PairWw
	}
	return 0
}

type MatchResultAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MatchConcluded bool                   `protobuf:"varint,3,opt,name=match_concluded,json=matchConcluded,proto3" json:"match_concluded,omitempty"` // 该 gatekeeper 对打已出结论
	Promoted       bool                   `protobuf:"varint,4,opt,name=promoted,proto3" json:"promoted,omitempty"`                                   // 新网络晋级 best
	BestSha        string                 `protobuf:"bytes,5,opt,name=best_sha,json=bestSha,proto3" json:"best_sha,omitempty"`                       // 晋级后的 best（未变则当前 best）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchResultAck) Reset() {
	*x = MatchResultAck{}
	mi := &file_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResultAck) ProtoMessage() {}

func (x *MatchResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResultAck.ProtoReflect.Descriptor instead.
func (*MatchResultAck) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *MatchResultAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *MatchResultAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MatchResultAck) GetMatchConcluded() bool {
	if x != nil {
		return x.MatchConcluded
	}
	return false
}

func (x *MatchResultAck) GetPromoted() bool {
	if x != nil {
		return x.Promoted
	}
	return false
}

func (x *MatchResultAck) GetBestSha() string {
	if x != nil {
		return x.BestSha
	}
	return ""
}

// 心跳 + 控制参数
type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CurrentThreads int32                  `protobuf:"varint,2,opt,name=current_threads,json=currentThreads,proto3" json:"current_threads,omitempty"`
	CompletedGames int32                  `protobuf:"varint,3,opt,name=completed_games,json=completedGames,proto3" json:"completed_games,omitempty"`
	RunningTaskId  string                 `protobuf:"bytes,4,opt,name=running_task_id,json=runningTaskId,proto3" json:"running_task_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentThreads() int32 {
	if x != nil {
		return x.CurrentThreads
	}
	return 0
}

func (x *HeartbeatRequest) GetCompletedGames() int32 {
	if x != nil {
		return x.CompletedGames
	}
	return 0
}

func (x *HeartbeatRequest) GetRunningTaskId() string {
	if x != nil {
		return x.RunningTaskId
	}
	return ""
}

type HeartbeatReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PauseSelfPlay    bool                   `protobuf:"varint,1,opt,name=pause_self_play,json=pauseSelfPlay,proto3" json:"pause_self_play,omitempty"`
	MctsSims         int32                  `protobuf:"varint,2,opt,name=mcts_sims,json=mctsSims,proto3" json:"mcts_sims,omitempty"` // 覆盖值，0 表示不覆盖
	Temperature      float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	PlayoutCapRandom bool                   `protobuf:"varint,4,opt,name=playout_cap_random,json=playoutCapRandom,proto3" json:"playout_cap_random,omitempty"`
	BestNetwork      string                 `protobuf:"bytes,5,opt,name=best_network,json=bestNetwork,proto3" json:"best_network,omitempty"` // 当前 best sha（供 worker 判断是否换网）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatReply) GetPauseSelfPlay() bool {
	if x != nil {
		return x.PauseSelfPlay
	}
	return false
}

func (x *HeartbeatReply) GetMctsSims() int32 {
	if x != nil {
		return x.MctsSims
	}
	return 0
}

func (x *HeartbeatReply) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *HeartbeatReply) GetPlayoutCapRandom() bool {
	if x != nil {
		return x.PlayoutCapRandom
	}
	return false
}

func (x *HeartbeatReply) GetBestNetwork() string {
	if x != nil {
		return x.BestNetwork
	}
	return ""
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\tscheduler\"\xb1\x01\n" +
	"\vTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x05R\athreads\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x03R\bmemoryMb\x12'\n" +
	"\x0fcurrent_network\x18\x05 \x01(\tR\x0ecurrentNetwork\"\xe9\x02\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x13.scheduler.TaskKindR\x04kind\x12\x1f\n" +
	"\vnetwork_sha\x18\x03 \x01(\tR\n" +
	"networkSha\x12!\n" +
	"\fopponent_sha\x18\x04 \x01(\tR\vopponentSha\x12\x1f\n" +
	"\vnetwork_url\x18\x05 \x01(\tR\n" +
	"networkUrl\x12!\n" +
	"\fopponent_url\x18\x06 \x01(\tR\vopponentUrl\x12,\n" +
	"\x12network_sha_remote\x18\a \x01(\tR\x10networkShaRemote\x12\x14\n" +
	"\x05games\x18\b \x01(\x05R\x05games\x121\n" +
	"\x06params\x18\t \x01(\v2\x19.scheduler.SelfPlayParamsR\x06params\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\"\xba\x01\n" +
	"\x0eSelfPlayParams\x12\x1b\n" +
	"\tmcts_sims\x18\x01 \x01(\x05R\bmctsSims\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12,\n" +
	"\x12playout_cap_random\x18\x03 \x01(\bR\x10playoutCapRandom\x12\x18\n" +
	"\avariant\x18\x04 \x01(\tR\avariant\x12!\n" +
	"\fextra_config\x18\x05 \x01(\tR\vextraConfig\"\xa8\x02\n" +
	"\vEpisodeMeta\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"game_count\x18\x03 \x01(\x05R\tgameCount\x12\x1f\n" +
	"\vtotal_steps\x18\x04 \x01(\x05R\n" +
	"totalSteps\x12\x16\n" +
	"\x06winner\x18\x05 \x01(\x05R\x06winner\x12\x1f\n" +
	"\vnetwork_sha\x18\x06 \x01(\tR\n" +
	"networkSha\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12%\n" +
	"\x0econtent_length\x18\b \x01(\x03R\rcontentLength\x12%\n" +
	"\x0econtent_sha256\x18\t \x01(\tR\rcontentSha256\"\x80\x01\n" +
	"\n" +
	"EpisodeAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x03 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tR\tobjectKey\"\"\n" +
	"\x0eNetworkRequest\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\"\x97\x01\n" +
	"\vNetworkInfo\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x17\n" +
	"\ais_best\x18\x04 \x01(\bR\x06isBest\x12\x1b\n" +
	"\tgame_data\x18\x05 \x01(\tR\bgameData\"~\n" +
	"\x16RegisterNetworkRequest\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\x12\x1d\n" +
	"\n" +
	"parent_sha\x18\x02 \x01(\tR\tparentSha\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x03 \x01(\tR\tuploadUrl\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"r\n" +
	"\x12RegisterNetworkAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x0fmatch_task_hint\x18\x03 \x01(\tR\rmatchTaskHint\"\x85\x03\n" +
	"\vMatchResult\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12'\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x13.scheduler.TaskKindR\x04kind\x12\x1f\n" +
	"\vnetwork_sha\x18\x04 \x01(\tR\n" +
	"networkSha\x12!\n" +
	"\fopponent_sha\x18\x05 \x01(\tR\vopponentSha\x12\x14\n" +
	"\x05games\x18\x06 \x01(\x05R\x05games\x12\x12\n" +
	"\x04wins\x18\a \x01(\x05R\x04wins\x12\x16\n" +
	"\x06losses\x18\b \x01(\x05R\x06losses\x12\x14\n" +
	"\x05draws\x18\t \x01(\x05R\x05draws\x12\x17\n" +
	"\apair_ll\x18\n" +
	" \x01(\x05R\x06pairLl\x12\x17\n" +
	"\apair_ld\x18\v \x01(\x05R\x06pairLd\x12\x17\n" +
	"\apair_dd\x18\f \x01(\x05R\x06pairDd\x12\x17\n" +
	"\apair_dw\x18\r \x01(\x05R\x06pairDw\x12\x17\n" +
	"\apair_ww\x18\x0e \x01(\x05R\x06pairWw\"\xa6\x01\n" +
	"\x0eMatchResultAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fmatch_concluded\x18\x03 \x01(\bR\x0ematchConcluded\x12\x1a\n" +
	"\bpromoted\x18\x04 \x01(\bR\bpromoted\x12\x19\n" +
	"\bbest_sha\x18\x05 \x01(\tR\abestSha\"\xa9\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12'\n" +
	"\x0fcurrent_threads\x18\x02 \x01(\x05R\x0ecurrentThreads\x12'\n" +
	"\x0fcompleted_games\x18\x03 \x01(\x05R\x0ecompletedGames\x12&\n" +
	"\x0frunning_task_id\x18\x04 \x01(\tR\rrunningTaskId\"\xc8\x01\n" +
	"\x0eHeartbeatReply\x12&\n" +
	"\x0fpause_self_play\x18\x01 \x01(\bR\rpauseSelfPlay\x12\x1b\n" +
	"\tmcts_sims\x18\x02 \x01(\x05R\bmctsSims\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12,\n" +
	"\x12playout_cap_random\x18\x04 \x01(\bR\x10playoutCapRandom\x12!\n" +
	"\fbest_network\x18\x05 \x01(\tR\vbestNetwork*=\n" +
	"\bTaskKind\x12\r\n" +
	"\tTASK_NONE\x10\x00\x12\x11\n" +
	"\rTASK_SELFPLAY\x10\x01\x12\x0f\n" +
	"\vTASK_RATING\x10\x022\xb1\x03\n" +
	"\x10SchedulerService\x12:\n" +
	"\aGetTask\x12\x16.scheduler.TaskRequest\x1a\x17.scheduler.TaskResponse\x12>\n" +
	"\rReportEpisode\x12\x16.scheduler.EpisodeMeta\x1a\x15.scheduler.EpisodeAck\x12?\n" +
	"\n" +
	"GetNetwork\x12\x19.scheduler.NetworkRequest\x1a\x16.scheduler.NetworkInfo\x12S\n" +
	"\x0fRegisterNetwork\x12!.scheduler.RegisterNetworkRequest\x1a\x1d.scheduler.RegisterNetworkAck\x12F\n" +
	"\x11ReportMatchResult\x12\x16.scheduler.MatchResult\x1a\x19.scheduler.MatchResultAck\x12C\n" +
	"\tHeartbeat\x12\x1b.scheduler.HeartbeatRequest\x1a\x19.scheduler.HeartbeatReplyB\x11Z\x0fbanqi/server/pbb\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_scheduler_proto_goTypes = []any{
	(TaskKind)(0),                  // 0: scheduler.TaskKind
	(*TaskRequest)(nil),            // 1: scheduler.TaskRequest
	(*TaskResponse)(nil),           // 2: scheduler.TaskResponse
	(*SelfPlayParams)(nil),         // 3: scheduler.SelfPlayParams
	(*EpisodeMeta)(nil),            // 4: scheduler.EpisodeMeta
	(*EpisodeAck)(nil),             // 5: scheduler.EpisodeAck
	(*NetworkRequest)(nil),         // 6: scheduler.NetworkRequest
	(*NetworkInfo)(nil),            // 7: scheduler.NetworkInfo
	(*RegisterNetworkRequest)(nil), // 8: scheduler.RegisterNetworkRequest
	(*RegisterNetworkAck)(nil),     // 9: scheduler.RegisterNetworkAck
	(*MatchResult)(nil),            // 10: scheduler.MatchResult
	(*MatchResultAck)(nil),         // 11: scheduler.MatchResultAck
	(*HeartbeatRequest)(nil),       // 12: scheduler.HeartbeatRequest
	(*HeartbeatReply)(nil),         // 13: scheduler.HeartbeatReply
}
var file_scheduler_proto_depIdxs = []int32{
	0,  // 0: scheduler.TaskResponse.kind:type_name -> scheduler.TaskKind
	3,  // 1: scheduler.TaskResponse.params:type_name -> scheduler.SelfPlayParams
	0,  // 2: scheduler.MatchResult.kind:type_name -> scheduler.TaskKind
	1,  // 3: scheduler.SchedulerService.GetTask:input_type -> scheduler.TaskRequest
	4,  // 4: scheduler.SchedulerService.ReportEpisode:input_type -> scheduler.EpisodeMeta
	6,  // 5: scheduler.SchedulerService.GetNetwork:input_type -> scheduler.NetworkRequest
	8,  // 6: scheduler.SchedulerService.RegisterNetwork:input_type -> scheduler.RegisterNetworkRequest
	10, // 7: scheduler.SchedulerService.ReportMatchResult:input_type -> scheduler.MatchResult
	12, // 8: scheduler.SchedulerService.Heartbeat:input_type -> scheduler.HeartbeatRequest
	2,  // 9: scheduler.SchedulerService.GetTask:output_type -> scheduler.TaskResponse
	5,  // 10: scheduler.SchedulerService.ReportEpisode:output_type -> scheduler.EpisodeAck
	7,  // 11: scheduler.SchedulerService.GetNetwork:output_type -> scheduler.NetworkInfo
	9,  // 12: scheduler.SchedulerService.RegisterNetwork:output_type -> scheduler.RegisterNetworkAck
	11, // 13: scheduler.SchedulerService.ReportMatchResult:output_type -> scheduler.MatchResultAck
	13, // 14: scheduler.SchedulerService.Heartbeat:output_type -> scheduler.HeartbeatReply
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		EnumInfos:         file_scheduler_proto_enumTypes,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
