[env]
LIBTORCH = { value = "/home/ynk/miniconda3/lib/python3.13/site-packages/torch", relative = false }
LD_LIBRARY_PATH = { value = "/home/ynk/miniconda3/lib/python3.13/site-packages/torch/lib", relative = false }